bundler_args: "--without development:production"
install: bin/wad
script: bundle exec rspec
language: ruby
rvm:
- 2.1.3
notifications:
  campfire:
    rooms:
    - secure: |-
        eEuzoYFXLPeIMt+zHGzZp6XCvbfxRDe8FA3kVwrNRB0zoOktPRZXD9O8ng2z
        x2Yg8C7i1unstuW0bjPvwphpdxJOTFSxliw6P4Xk1Y9HnTYQqqUbDat/zL9c
        AyjYezuRQgYFSBP2BgNZ2RL9RiLSyLQBWhcHGB0yBS6rsheKWbk=
    on_success: never
    on_failure: always
  webhooks: http://cfa-project-monitor.herokuapp.com/projects/67f80d53-afb0-4344-bd40-2644f55a4462/status
env:
  global:
  - S3_BUCKET_NAME=gems-for-travis
  - OHANA_API_ENDPOINT=http://ohana-api-test.herokuapp.com/api
  - DOMAIN_NAME=lvh.me
  - secure: TbS1XZyUYTYm9YjW2ATWk8LHaVwWQO5Onm81hkWM/FZasUfk2gbVOMuXTag+2Wif5cBd2dhVFaLZmROdqaXk1U52m/s6snfWNqJa1olEA0GEWFLwimvouAsUpl4JB1jKTiIN81MUdBv4espLYD/f5sbM5/a4ZoYPUXutfI+YItg=
